import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.room)
    alias(libs.plugins.aboutlibraries)
}

// This repository starts from a code-only snapshot (no prior history), so the
// version is pinned here instead of being derived from git. Bump both on each
// release; CI/local builds may still override with -PversionCode / -PversionName:
//   ./gradlew :composeApp:bundleStoreRelease -PversionCode=42
val gitVersionCode: Int = (findProperty("versionCode") as String?)?.toIntOrNull() ?: 35
val gitVersionName: String = (findProperty("versionName") as String?) ?: "0.1.5"

// RevenueCat public SDK keys stay out of git: a fork or CI build without them
// gets the placeholders → NoopSupportRepository ("unavailable", spec 004).
// Lookup order: -Prevenuecat.androidKey=… · env REVENUECAT_ANDROID_KEY ·
// gitignored local.properties (same for iosKey / REVENUECAT_IOS_KEY).
val localProperties = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}
fun revenueCatKey(property: String, env: String, placeholder: String): String =
    providers.gradleProperty(property).orNull
        ?: providers.environmentVariable(env).orNull
        ?: localProperties.getProperty(property)
        ?: placeholder
val revenueCatAndroidKey = revenueCatKey("revenuecat.androidKey", "REVENUECAT_ANDROID_KEY", "goog_PLACEHOLDER")
val revenueCatIosKey = revenueCatKey("revenuecat.iosKey", "REVENUECAT_IOS_KEY", "appl_PLACEHOLDER")

abstract class GenerateRevenueCatKeys : DefaultTask() {
    @get:Input abstract val androidKey: Property<String>
    @get:Input abstract val iosKey: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val keys = mapOf("ANDROID" to androidKey.get(), "IOS" to iosKey.get())
        keys.forEach { (name, key) ->
            require(Regex("[A-Za-z0-9_]+").matches(key)) { "RevenueCat $name key has unexpected characters" }
        }
        val file = outputDir.file("de/einsatzlog/app/support/RevenueCatKeys.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("// Generated by :composeApp:generateRevenueCatKeys — do not edit, do not commit.")
                appendLine("package de.einsatzlog.app.support")
                appendLine()
                appendLine("internal object RevenueCatKeys {")
                keys.forEach { (name, key) -> appendLine("    const val $name = \"$key\"") }
                appendLine("}")
            },
        )
    }
}

val generateRevenueCatKeys = tasks.register<GenerateRevenueCatKeys>("generateRevenueCatKeys") {
    androidKey.set(revenueCatAndroidKey)
    iosKey.set(revenueCatIosKey)
    outputDir.set(layout.buildDirectory.dir("generated/revenuecat/kotlin"))
}

// The SDK crashes on purpose with a Test Store key in a release build — fail the build instead.
tasks.matching { it.name.matches(Regex("(bundle|assemble)StoreRelease")) }.configureEach {
    val androidKey = revenueCatAndroidKey
    doFirst {
        check(!androidKey.startsWith("test_")) {
            "revenuecat.androidKey is a Test Store key — use the goog_ key for release builds."
        }
    }
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateRevenueCatKeys)
        }
        commonMain.dependencies {
            // Presentation layer — also brings the Compose artifacts, the
            // generated resources and the shared UI types along transitively.
            implementation(projects.ui)

            implementation(libs.room.runtime)
            implementation(libs.sqlite.bundled)

            implementation(libs.purchases.kmp.core)
            implementation(libs.aboutlibraries.compose.m3)

            implementation(project.dependencies.platform(libs.koin.bom))
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

            implementation(libs.jb.lifecycle.viewmodel.compose)
            implementation(libs.jb.lifecycle.runtime.compose)
            implementation(libs.jb.navigation.compose)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.koin.android)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

android {
    namespace = "de.einsatzlog.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "de.einsatzlog.app"
        minSdk = 26
        targetSdk = 36
        versionCode = gitVersionCode
        versionName = gitVersionName
    }

    // Reads a gitignored keystore.properties when present (Michal keeps
    // custody); falls back to debug signing so release always builds.
    val keystorePropsFile = rootProject.file("keystore.properties")
    if (keystorePropsFile.exists()) {
        val props = Properties().apply { keystorePropsFile.inputStream().use { load(it) } }
        signingConfigs.create("release") {
            storeFile = rootProject.file(props.getProperty("storeFile"))
            storePassword = props.getProperty("storePassword")
            keyAlias = props.getProperty("keyAlias")
            keyPassword = props.getProperty("keyPassword")
        }
    }

    // `store` = Play/App Store build (Crashlytics + RevenueCat land here in later slices).
    // `foss` = no proprietary services, F-Droid-compatible (see specs/004 for the seam strategy).
    flavorDimensions += "distribution"
    productFlavors {
        create("store") {
            dimension = "distribution"
            isDefault = true
        }
        create("foss") {
            dimension = "distribution"
            applicationIdSuffix = ".foss"
            versionNameSuffix = "-foss"
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("release") ?: signingConfigs.getByName("debug")
        }
    }

    buildFeatures {
        buildConfig = true // flavor detection for the purchases seam (spec 004)
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

dependencies {
    add("kspAndroid", libs.room.compiler)
    add("kspIosArm64", libs.room.compiler)
    add("kspIosSimulatorArm64", libs.room.compiler)
}

room {
    schemaDirectory("$projectDir/schemas")
}
