import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
}

// The only module that knows RevenueCat. `:composeApp` links it for iOS and
// for the Android `store` flavor; the `foss` flavor never sees it, so no
// proprietary code (Play Billing, Play Services, Firebase) reaches that APK.

// RevenueCat public SDK keys stay out of git: a fork or CI build without them
// gets the placeholders → NoopSupportRepository ("unavailable", spec 004).
// Lookup order: -Prevenuecat.androidKey=… · env REVENUECAT_ANDROID_KEY ·
// gitignored local.properties (same for iosKey / REVENUECAT_IOS_KEY).
val localProperties = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}
fun revenueCatKey(property: String, env: String, placeholder: String): String =
    providers.gradleProperty(property).orNull
        ?: providers.environmentVariable(env).orNull
        ?: localProperties.getProperty(property)
        ?: placeholder

abstract class GenerateRevenueCatKeys : DefaultTask() {
    @get:Input abstract val androidKey: Property<String>
    @get:Input abstract val iosKey: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val keys = mapOf("ANDROID" to androidKey.get(), "IOS" to iosKey.get())
        keys.forEach { (name, key) ->
            require(Regex("[A-Za-z0-9_]+").matches(key)) { "RevenueCat $name key has unexpected characters" }
        }
        val file = outputDir.file("de/einsatzlog/app/support/RevenueCatKeys.kt").get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                appendLine("// Generated by :purchases-revenuecat:generateRevenueCatKeys — do not edit, do not commit.")
                appendLine("package de.einsatzlog.app.support")
                appendLine()
                appendLine("internal object RevenueCatKeys {")
                keys.forEach { (name, key) -> appendLine("    const val $name = \"$key\"") }
                appendLine("}")
            },
        )
    }
}

val generateRevenueCatKeys = tasks.register<GenerateRevenueCatKeys>("generateRevenueCatKeys") {
    androidKey.set(revenueCatKey("revenuecat.androidKey", "REVENUECAT_ANDROID_KEY", "goog_PLACEHOLDER"))
    iosKey.set(revenueCatKey("revenuecat.iosKey", "REVENUECAT_IOS_KEY", "appl_PLACEHOLDER"))
    outputDir.set(layout.buildDirectory.dir("generated/revenuecat/kotlin"))
}

kotlin {
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }

    iosArm64()
    iosSimulatorArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateRevenueCatKeys)
        }
        commonMain.dependencies {
            // SupportRepository, SupportProduct, … live in :ui.
            implementation(projects.ui)
            implementation(libs.purchases.kmp.core)
        }
    }
}

android {
    namespace = "de.einsatzlog.app.purchases"
    compileSdk = 36

    defaultConfig {
        minSdk = 26
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}
